image: ubuntu

configuration: Release

init:
- appveyor version

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build:
  publish_nuget: true
  publish_aspnet_core: true
  publish_core_console: true
  verbosity: minimal

deploy:
#- provider: FTP
#  host: waws-prod-bay-003.ftp.azurewebsites.windows.net
#  protocol: ftp
#  username: ftp-test\$ftp-test
#  password:
#    secure: I/+uF9anRC6vIknmdRuhEQwsYhZDy4thwVVMxtwSC2N+Q4p1A9ximQEnVMBlGa8bxjifQlGqPJuU78cZNinixw==
#  folder: /site/wwwroot
#  application: AspNetCoreApp
#  beta: false

- provider: AzureAppServiceZipDeploy
  website: ftp-test
  username: ftp-test-deploy
  password:
    secure: I/+uF9anRC6vIknmdRuhEQwsYhZDy4thwVVMxtwSC2N+Q4p1A9ximQEnVMBlGa8bxjifQlGqPJuU78cZNinixw==
  artifact: AspNetCoreApp

- provider: Environment
  name: webhook-test

- provider: NuGet
  api_key:
    secure: 9Tf+1T2tB/qiqZTkQFpNbz3jboYpvOo/ZQ4M+0xfw07jETCSaQyi26wCQT3tHodc
